### ISSUE TITLE
[Request] Self-closing tag

### ISSUE THREAD

**Issue by binyamin** [saurabhdaware/DEV-widget#12]
I'm not familiar with `mjs`, so I don't even know if it's possible. But, since the card requires no children when it initializes itself, can you make the tag self closing (`<dev-widget data-username="foo" />`)? Currently, the browser will automatically close the tag *after* whatever content comes next. ~~See [example](https://codepen.io/b3u/pen/eYYPway) on Codepen.~~ (Example gone)

**Comment by binyamin** [comment]
wontfix (see [ref](https://developers.google.com/web/fundamentals/web-components/customelements))

**Comment by saurabhdaware** [comment]
Yeah, I would love to see this but apparently its a limitation from the web components side. I don't think so there will be any changes to this. here's an issue on web components GitHub https://github.com/w3c/webcomponents/issues/624

**Comment by binyamin** [comment]
Maybe make a note on the readme? "Like all custom elements, use a closing tag".
@saurabhdaware
