### ISSUE TITLE
hard coded alt attribute

### ISSUE THREAD

**Issue by vintagesucks** [saurabhdaware/DEV-widget#8]
https://github.com/saurabhdaware/DEV-widget/blob/cee24f315594a50954c75b13aa6305506e39223f/src/card.component.mjs#L9

`Saurabh Daware's DEV Profile` is currently hard coded in the widget.

**Comment by saurabhdaware** [comment]
whoops totally missed this! would you like to contribute? we can either create logo dynamically with other code or simply put alt tag dynamically,

I think second option would be better (so the image will load before the card is created)

Let me know if you want to work on this and thank you for pointing this out

**Comment by ynfle** [comment]
The `alt` attribute that @vintagesucks was referring to is referring to the DEV logo, not the user's logo. The profile picture doesn't have any alt text.
